POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "testi blogi",
  "author": "testi käyttäjä",
  "url": "https://fullstackopen.com/osa4/backendin_testaaminen",
  "likes": 3
}


###
# lisätään uusi blogi userId:lle http://localhost:3001/api/users
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "User id of the blog creator ...",
  "author": "testi käyttäjä",
  "url": "https://fullstackopen.com/osa4/backendin_testaaminen",
  "likes": 30,
  "userId": "5d081937cb1302139a7fbd82"
}

###
# lisätään toinen blogi samalle userId:lle
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Toinen blogi samalle userId:lle",
  "author": "testi käyttäjä",
  "url": "https://fullstackopen.com/osa4/backendin_testaaminen",
  "likes": 60,
  "userId": "5d081937cb1302139a7fbd82"
}

###
# Muistiinpanojen luominen vain kirjautuneille
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI1ZDA4MTkzN2NiMTMwMjEzOWE3ZmJkODIiLCJpYXQiOjE1NjA4NTM3NjJ9.rZZl2yKJsm2DJPAycEkAQKeA1u0hDPU3Pmp49eBqQto

{
  "title": "Muistiinpanojen luominen vain kirjautuneille",
  "author": "testi käyttäjä",
  "url": "https://fullstackopen.com/osa4/backendin_testaaminen",
  "likes": 99
}